### ISSUE TITLE
mob drops

### ISSUE THREAD

**Issue by Klicer** [Jikoo/MobStacker#1]
Killing 100+ blazes only gives you a small amount of blaze rods. Don't know if its a bug or fixable in config, but I just tested with a player, he killed a stack of a bunch of blazes and went from level 3 to 32, but only got 3 blaze rods.

**Comment by Jikoo** [comment]
Anything in console when killing blazes? Unfortunately stack loot is somewhat problematic due to changes in 1.14, context isn't always allowed, and there's no way to check beforehand which contexts are required and which are not allowed.

**Comment by Jikoo** [comment]
I guess I could parse the exception message to handle cases more gracefully.

**Comment by Jikoo** [comment]
Looks like this was recently fixed on Spigot's end in [f7d6ad53eeb](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f7d6ad53eeb1ad3a4372cc73fe77eac4e01a9470)
